### ISSUE TITLE
match-lambda: no matching clause for '()

### ISSUE THREAD

**Issue by jsmaniac** [racket/datalog#1]
I'm using racket 6.4.0.4, and get the following error when trying to run a datalog file in drracket:

```
/usr/share/racket/pkgs/datalog/pretty.rkt:9:2: match-lambda: no matching clause for '()
```

Here is the datalog file:

```racket
#lang datalog
type(z, tz). listof(tz, ez). int(ez).
casepair(z, za, tza, zb, tzb).
pair(TA, TE, null) :- casepair(V, VA, TA, VB, TB), type(V, TV), listof(TV, TE).
pair(A, B, C)?
```

Please tell me if I can provide any extra information.

**Comment by jsmaniac** [comment]
The problem seems to be caused by my `null` identifier.

**Comment by jeapostrophe** [comment]
I just pushed a fix... I'm curious as to what you were expecting. The current commit assumes that you meant '() and that this is a printing error. An alternative account is that you meant a Datalog anonymous literal printed as null.

https://github.com/racket/datalog/commit/84a3b742aea18d7590f3dd6cbe6e4b5738b93203

**Comment by jsmaniac** [comment]
@jeapostrophe Thanks for the quick fix.

I was toying with the idea of writing a typechecker using datalog rules. I hadn't realized at first that `null` would be interpreted as `'()`. I just meant it to be an anonymous literal, and thought the result would be `pair(tza, ez, null).`, but the use of `null` here was a mistake from my part, that uncovered the crash.

**Comment by rfindler** [comment]
Would it have helped if DrRacket had drawn the correct arrow (from "null"
to the "datalog" on the first line)?

**Comment by jsmaniac** [comment]
@rfindler That would be nice to have indeed. Are there any arrows drawn in `#lang datalog` ? I see that in `add1(x) :- x.`, the `add1` is underlined in light green, and one can access the doc via a right-click, but no arrows are drawn.

**Comment by rfindler** [comment]
In the original program in this PR, there are arrows for TA and TE.

It shouldn't be too hard to get an arrow for null too, I would think.

**Comment by jsmaniac** [comment]
I'm closing this and opening another issue for the arrows.
