### ISSUE TITLE
the syntax colorer lexer doesn't obey the contract it should

### ISSUE THREAD

**Issue by rfindler** [racket/datalog#12]
Running the below in the context of syntax-color.rkt produces errors (like the one below). 

It may also be a good idea to put `lexer/c` on the export directly.

Here is a simple example too. This program also produces an error:

```
#lang datalog

"\n"
```

Here's a transcript of one of the errors you get when using the contract.

```
Welcome to DrRacket, version 7.4.0.4--2019-08-07(c72194ca/d/define-region) [3m].
Language: racket/base, with debugging; memory limit: 512 MB.
> (require racket/contract syntax-color/lexer-contract)
> (for ([x (in-range 10000)])
    (contract lexer/c get-syntax-token 'pos 'neg))
. . ../../parser-tools-lib/parser-tools/lex.rkt:145:39: try-some-random-streams: random testing of lexer failed
  lexer: #<procedure:get-syntax-token>
  pseudo-random state: #(2992410306 64795275 1447620449 189944826 3275941387 3238031739)
  latest input string: "()÷)Σ\u0000\u0000\u0095\u0014N»\fbØM\u0095λλ |Ê)|Ü¢S)|÷r\u0096I@êû|y\u001A\u00AD||û||¯EA\u0000\"ßΣ\\λ,\"RGñùµ6}ìt(;À{ý})~i (X[]1{åx}Î\u0019("
  error message: "lexer: No match found in input starting with: \\λ"
> 
```

**Comment by jeapostrophe** [comment]
I don't understand. I don't see any contract violations here. It is a contract violation to throw an error message on illegal input? I don't see anywhere in the `start-colorer` docs that says the function must be total.

**Comment by rfindler** [comment]
lexers are supposed to live up to lexer/c (which this one doesn't), so that's a contract violation.

And yes, the colorer should color any buffer, turning things read. 

Try opening an unclosed string in a DrRacket window and you'll see that the colorer colors things red (it doesn't raise an error).

**Comment by jeapostrophe** [comment]
I found a way to make it total. The docs don't say it should be total and I still haven't found a `lexer/c` violation.

**Comment by rfindler** [comment]
The code example I posted above shows you a `lexer/c` violation (for the version before your change, tho!)

**Comment by jeapostrophe** [comment]
In that example, my code threw an exception and some other code (not mine) converted it into a single value rather than the allowed 5 or 7. There's no path through my code that returned 1 value.

**Comment by rfindler** [comment]
One commit `0e9ac8a96a7`, I see the below, so I think the lexer isn't quite total yet.

```
Welcome to DrRacket, version 7.4.0.4--2019-08-07(19fad3f8/d) [cs].
Language: racket/base, with debugging; memory limit: 512 MB.
> (require racket/contract syntax-color/lexer-contract)
> (for ([x (in-range 10000)])
    (contract lexer/c get-syntax-token 'pos 'neg))
. . ../../../../../../exp/plt/racket/share/pkgs/parser-tools-lib/parser-tools/lex.rkt:145:39: try-some-random-streams: random testing of lexer failed
  lexer: #<procedure:get-syntax-token>
  pseudo-random state: #(1451279166 3509327232 1345754703 598336301 3647687717 2485993732)
  latest input string: "\"\\}\n{}\"û@F\n`ª\"\"~\e\u009A\u0081Ä)| ||\"\"|\"}ô|ü\"û\u0081±\"@u|ΣZ}\"\u00955í;/@ýG\u0001λþ\u0082)Pbù\"\"\u0018Σþ\u008CÁ\"\"h*)W|!"
  error message: "lexer: No match found in input starting with: \\}"
> 
```

**Comment by jeapostrophe** [comment]
I put this in `datalog/tool/syntax-color.rkt`:

```
(module+ test
  (define p (open-input-string "\"\\}\n{}\"û@F\n`ª\"\"~\e\u009A\u0081Ä)| ||\"\"|\"}ô|ü\"û\u0081±\"@u|ΣZ}\"\u00955í;/@ýG\u0001λþ\u0082)Pbù\"\"\u0018Σþ\u008CÁ\"\"h*)W|!"))
  (let loop ()
    (define-values (lex sym b c d) (get-syntax-token p))
    (unless (eq? 'eof sym)
      (printf "~a(~v)\n" sym lex)
      (loop))))
```

And I get no errors. Is this the wrong test?

**Comment by rfindler** [comment]
I think I must have made a mistake in my previous comment. I'm not seeing any errors now either.
