### ISSUE TITLE
REPL does not work with #lang datalog

### ISSUE THREAD

**Issue by jsmaniac** [racket/datalog#2]
The REPL doesn't work with `#lang datalog`.

Steps to reproduce:
1) Create a file containing just the line `#lang datalog`
2) At the REPL, enter `foo(a, b).`
3) The following error message is shown:

```
 > foo(a, b).
theory: undefined;
 cannot reference an identifier before its definition
```

Racket version:
6.4.0.8

**Comment by jsmaniac** [comment]
`git bisect` points out the commit `a0d3481 fix for new syntax expander, thanks mflatt!`

The problem seems to be with this hunk:

```
+    (quasisyntax/loc src
+      #,(compile-program
+         (parameterize ([current-source-name src])
+           (parse-program in))))))
-    (compile-program
-     (parameterize ([current-source-name src])
-       (parse-program in)))))
```

I think that quasisyntax/loc adds some scopes to the syntax object. Unfortunately, we can't call `syntax-local-introduce` because this happens inside the reader, so it would give the error `syntax-local-introduce: not currently transforming`

**Comment by Jonathan50** [comment]
I have this issue too.

**Comment by jsmaniac** [comment]
@Jonathan50 I believe this was fixed in recent versions. It works fine for me using the latest snapshot, `20160510-d92be80` from https://plt.eecs.northwestern.edu/snapshots/ . Could you check if it works for you using that version?

**Comment by Jonathan50** [comment]
```
$ racket --version
Welcome to Racket v6.3.
$ 
```
Wait, according to racket.org version 6.5 is out?
According to https://www.parabola.nu/packages/community/x86_64/racket/ the Racket version Parabola has is 6.5-1. `pacman -Syu` outputs `there is nothing to do`. It seems my Parabola installation is somehow broken...

**Comment by jsmaniac** [comment]
@Jonathan50 Can't help as I haven't used Arch nor Parabola (yet). As a fallback, the manual installation is very easy though. It's just a matter of running `chmod +x racket-6.5-x86_64-linux.sh` and `./racket-6.5-x86_64-linux.sh`, and answering a few questions.

Since I think the problem has been fixed in more recent versions, I'm closing this, but please open a new bug referring this one if you still have the problem with version 6.5. Thanks!
