### ISSUE TITLE
cannot re-define a constant (lifted.0)

### ISSUE THREAD

**Issue by SuzanneSoy** [racket/datalog#6]
I have a rather large program which generates then queries a datalog database. After wrapping it as a `#lang`, I get the following error at run-time:

```racket
define-values: assignment disallowed;
 cannot re-define a constant
  constant: lifted.0
```

During the generation, some clauses are dynamically generated and inserted into the database with:
```racket
(eval `(datalog! global-variable-thy
                 (! (:- (foo a)
                        ,@literals)))
      (variable-reference->namespace (#%variable-reference)))
```

The `eval` seems to be the cause of the error, removing that expression makes the file run fine.

I used the following workaround to get datalog to work inside `eval`:

```racket
(eval `(let ()
         (define-syntax (circumvent stx)
           (syntax-case stx ()
             [(_ dl)
              (local-expand/capture-lifts #'dl 'expression '())]))
         (circumvent
          (datalog! global-variable-thy
                    (! (:- (foo a)
                           ,@literals)))))
      (variable-reference->namespace (#%variable-reference)))
```

Unfortunately I can't share the full code right now (company code).

**Comment by jeapostrophe** [comment]
I tried this test case and got no error. I suspect that the error has something to do with the particular value of `literals`. Is it protected by a contract?

```
#lang racket/base
(require datalog)

(module+ test
  (define global-variable-thy (make-theory))
  (define literals '(la lb lc))
  
  (eval `(datalog! global-variable-thy
                   (! (:- (foo a) ,@literals)))
        (variable-reference->namespace (#%variable-reference))))
```

**Comment by jsmaniac** [comment]
@jeapostrophe Thanks for looking into this. I managed to build a minimal example:

```
#lang racket/base

(require datalog)

(define global-variable-thy (make-theory))

;; No error if the following line is commented out
(define (bar) (datalog global-variable-thy (? (blah A))))

(eval
 `(let ()
    (datalog! global-variable-thy
              (! (:- (foo a b c)))))
 (variable-reference->namespace (#%variable-reference)))
```

It seems that the error only happens if `(datalog …)` is used both inside eval and outside. Here, the "outside" use is not even executed. Furthermore, it seems that the "outside" use must be a query, changing bar's body to `(datalog global-variable-thy (! (:- (blah A))))`   does not trigger the error.

**Comment by jeapostrophe** [comment]
@jsmaniac I've reduced this to an interaction between the syntax system and the contract system. Let's let @mflatt and @rfindler have a look

```
#lang racket/base

(module src racket/base
  (define (src x) x)
  (provide src))

(module csrc racket/base
  (require (submod ".." src)
           racket/contract)
  (provide
   (contract-out
    [src (-> number? number?)])))

(module mac racket/base
  (require (submod ".."
                   ;; Works
                   #;src
                   ;; Doesn't work
                   csrc))
  (define-syntax-rule (mac x) (src x))
  (provide mac))

(module use racket/base
  (require (submod ".." mac))
  ;; Comment out this and it works:
  (define (outside) (mac 5))
  (eval `(mac 6)
        (variable-reference->namespace
         (#%variable-reference))))

(require (submod "." use))
```

**Comment by mflatt** [comment]
Errortrace also appears to be relevant, and it appears to be yet another problem related to saving a module context for later use via `variable-reference->namespace`. The reimplemented expander (a.k.a. the "linklet" branch) doesn't have this bug (because it marshals information in a simpler and more consistent way).

**Comment by LiberalArtist** [comment]
This seems to be working now (on Racket 8.8).
