### ISSUE TITLE
No #%top-interaction

### ISSUE THREAD

**Issue by iitalics** [racket/datalog#9]
`datalog` doesn't define `#%top-interaction`, so we don't get a REPL.

**Comment by jeapostrophe** [comment]
Back when I made it there was a parsing problem, we could review it and see if it is possible. I may have cycles to do this after Thanksgiving.

**Comment by jeapostrophe** [comment]
Alright, so this definitely does work, I'm not sure what you're seeing. Here's a picture:
<img width="1280" alt="datalog has repl" src="https://user-images.githubusercontent.com/232698/32986163-95ce714e-cc99-11e7-80ee-cc3c3b4c83cd.png">

**Comment by greghendershott** [comment]
It doesn't work for me on 6.10 or on a recent snapshot:

```
#lang datalog

edge(a, b). edge(b, c). edge(c, d). edge(d, a).
path(X, Y) :- edge(X, Y).
path(X, Y) :- edge(X, Z), path(Z, Y).

path(X, Y)?
```

```
$ /Applications/Racket_v6.90.0.30/bin/racket -qit datalog.rkt
Welcome to Racket v6.90.0.30.
path(a, a).
path(a, d).
path(a, c).
path(a, b).
path(b, a).
path(b, d).
path(b, c).
path(b, b).
path(c, a).
path(c, d).
path(c, c).
path(c, b).
path(d, b).
path(d, c).
path(d, d).
path(d, a).
> path(X, Y)?
path: undefined;
 cannot reference an identifier before its definition
  in module: top-level
  internal name: path
  context...:
   /Applications/Racket_v6.90.0.30/collects/racket/private/repl.rkt:11:26
> stdin::7: unquote: not in quasiquote
  in: (unquote Y)
  location...:
   stdin::7
  context...:
   raise-syntax-error
   for-loop
   expand-capturing-lifts
   expand-single
   temp74_1
   compile16
   temp68_1
   /Applications/Racket_v6.90.0.30/collects/racket/private/repl.rkt:11:26
> ?: undefined;
 cannot reference an identifier before its definition
  in module: top-level
  internal name: ?
  context...:
   /Applications/Racket_v6.90.0.30/collects/racket/private/repl.rkt:11:26
> 
```

---

[As for racket-mode, there is an additional problem that it's trying to be too "smart" about <kbd>ENTER</kbd>. Instead of being bound to `comint-send-input`, it's bound to a function that sees if you have a complete s-expr yet, and if not, just does `indent-and-newline`. Obviously that needs to stop being so smart, to work with non-s-expr langs. But then I'll encounter the equivalent of the above issue, probably?]

**Comment by jeapostrophe** [comment]
I don't know how to make #lang datalog work in the REPL, but #lang datalog/sexp does.

**Comment by jeapostrophe** [comment]
I don't know how to make it work on the REPL. I just know how to make it work in DrRacket.

**Comment by greghendershott** [comment]
I'm looking into getting this working with racket-mode.

- I am calling your provided `drracket:submit-predicate` to decide whether <kbd>RET</kbd> should submit. It returns `#t` for (say) `(open-input-string "path(X, Y)?")`.

- I am correctly detecting and loading your [`configure-runtime`](https://github.com/racket/datalog/blob/master/lang/configure-runtime.rkt). As a result, `current-read-interaction` is set to your `the-read` handler.

But when entering `path(X, Y)?` at the REPL, it seems to "hang". 😞

Now, if I try calling `the-read` directly on `current-input-port`:

```
$ pwd
/Applications/Racket_v6.10/share/pkgs/datalog/lang
$ TERM=dumb racket
Welcome to Racket v6.10.
> ,en configure-runtime.rkt
<pkgs>/datalog/lang/configure-runtime> (the-read "here" (current-input-port))
path(X,Y)?
```

and press <kbd>RET</kbd> -- it also "hangs". 

If I then _also_ type <kbd>C-d</kbd> to send end-of-file -- _now_ `the-read` returns:

```
#<syntax:3:0 (? (path X Y))>
```

It seems surprising for a `current-read-interaction` handler to wait for `eof`? 

Maybe this happens to work in DrRacket, but it seems like it's not going to work for "normal" input.

Could it instead just read one datalog expression at a time, e.g. up to the terminating `.` or `?`?

That way, this could work in racket-mode. It would also let it work in XREPL if that were enhanced to do configure-runtimes (either directly or by enhancing `racket/sandbox`.)

**Comment by greghendershott** [comment]
@rfindler Do you have any hints? I don't understand how, from racket-mode's `current-prompt-read` handler, to use a `current-read-interaction` handler like [this `configure-runtime.rkt`](https://github.com/racket/datalog/blob/master/lang/configure-runtime.rkt):

```racket

#lang racket/base

(define (configure data)
  (current-read-interaction the-read))
(provide configure)

(require datalog/parse
         datalog/private/compiler)

(define (the-read src ip)
  (cond
    [(or (not (char-ready? ip))
         (eof-object? (peek-char ip)))
     eof]
    [else
     (compile-statement
      (parameterize ([current-source-name src])
(parse-statement ip)))]))
```

With the default read-interaction handler (for sepxrs), I just call it and it returns syntax for an expression whenever that can be read from input.

But this one just immediately returns `eof` and ... I don't know what I'm supposed to do.

Yet somehow it works with DrRacket. I don't mind trying to reverse engineer this but I'm having trouble finding the place(s) and piece(s) that use this in the DrRacket source.  Any hints?

(Also, if/when I do finally understand it, I might try to submit a documentation PR for `current-read-interaction`?)

**Comment by greghendershott** [comment]
Update: With the sort of `current-prompt-read` handler described [here](https://github.com/greghendershott/racket-mode/issues/311#issuecomment-407541502):

```racket
(define/contract (make-prompt-read m)
  (-> (or/c #f mod?) (-> any))
  ;; A channel to which a thread puts interactions that it reads using
  ;; the current-read-interaction handler. This can be set by a lang
  ;; from its configure-runtime, so, this should be compatible with
  ;; any lang, even non-sexpr langs.
  (define ch (make-channel))
  (define (read-interaction/put-channel)
    (define in ((current-get-interaction-input-port)))
    (define v ((current-read-interaction) (object-name in) in))
    (channel-put ch v)
    (read-interaction/put-channel))
  (thread read-interaction/put-channel)
  ;; The prompt-read handler.
  (define (prompt-read)
    (match (sync/timeout 0 ch)
      ;; If no interaction ready, display prompt and wait.
      [#f
       (display-prompt (maybe-mod->prompt-string m))
       (channel-get ch)]
      ;; Another interaction ready, no need to prompt again.
      [v v]))
  prompt-read)
```

Now datalog seems to work in racket-repl-mode -- provided I make this change on the Emacs Lisp side (this happens when you press <kbd>RET</kbd>):

```elisp
         (comint-send-input)
         ;; Also sending EOF is necessary for some #lang's
         ;; current-read-interaction handlers, such as datalog's. As I
         ;; type this comment, I'm stating this as a new empirical
         ;; observation -- without actually understanding why!!
         (process-send-eof)
```

So as the comment says, "it works" ... but I don't really understand why.

And I mean, in a "normal" REPL, are people supposed to type a statement, then <kbd>RET</kbd>, then <kbd>C-d</kbd>?  That seems unusual.

**Comment by greghendershott** [comment]
If you're reading this in email, I edited the code in the [previous comment](https://github.com/racket/datalog/issues/9#issuecomment-407564330).

```diff
-    (channel-put ch v)
+    (cond [;; Deal with e.g. datalog's handler which returns eof when
+           ;; (char-ready? in) is #f.
+           (eof-object? v)
+           (sync in)]
+          [else (channel-put ch v)])
 ```

**Comment by greghendershott** [comment]
Actually, it looks like having Emacs do `process-send-eof` after sending the input is a bad idea -- on Windows it will terminate the subprocess: https://ftp.gnu.org/old-gnu/emacs/windows/docs/faq7.html#TOC98

The more I like at it, it seems like the root issue is that `parse-statement` doesn't stop after parsing one statement. For example:

```racket
(parse-statement (open-input-string "edge(a,b). node(b,c)"))
```

raises the error:

```racket
string:1:11: datalog: Unexpected token IDENTIFIER
  in: "node"
```

I guess DrRacket can insert EOF as a kind of "interaction separator".  But (a) that's not the documented behavior for using a [`current-read-interaction` handler](https://docs.racket-lang.org/reference/eval.html#(def._((quote._~23~25kernel)._current-read-interaction))) and (b) anyway it seems unlikely to work across platforms and tools?

To be clear I'm asking about both "sides" here, DrRacket and datalog.

**Comment by rfindler** [comment]
I was under the impression that streams typically terminate with eofs forever, but that that isn't required by the spec. (Not that I can point you to anything in any spec, for sure.) But putting this into the definitions in DrRacket or into Racket's REPL (on a mac) suggests that this is supposed to work:

```
(current-read-interaction
 (lambda (src in)
   (define chars
     (let loop ()
       (define c (read-char in))
       (if (eof-object? c)
           '()
           (cons c (loop)))))
   #`(writeln '#,chars)))
```

Maybe there is a way to keep these EOFs entirely inside the Racket part, and using some other mechanism to decide when you have enough data from Emacs?

As for `current-read-interaction`'s spec, I don't think that this issue has needed to be defined before because sexp-based languages have natural termination baked in based on the matching parens. So maybe it is time to define something?

**Comment by greghendershott** [comment]
That example works for me in macOS Terminal provided I type _both_ <kbd>RET</kbd> and <kbd>C-d</kbd> in that order. If I type just <kbd>C-d</kbd>, it just beeps at me and does nothing.

I can imagine designing a language that way and telling users of the lang: "Please press RET and C-d in that order". I can imagine doing that... but I'm having trouble imagining why?

In my experience REPL interactions are expressions or statements in the lang. Either they're newline terminated with some magic char like backslash for line continuations, or, the lang specifies a delimiter like semi-colon or period. And maybe `begin`-like syntax like curly brackets to supply > 1 expr per line. That's how I've seen langs handle one-or-more statements/expressions per one-or-more lines.

Admittedly, you've probably used more REPL langs than me. Is there some precedent I don't know about that we're trying to follow here, with EOF?

**Comment by rfindler** [comment]
Nope, no precedent. And given that things tend to be line-buffered (for editing purposes) and that's pretty well-established, maybe we should change things to not put EOFs into the stream anymore, and then make everyone change their readers to work in that situation. 

I'm not sure how much of an impact that would have, tho.
